package org.cyberrealm.tech.muvio.model;

public enum TopLists {
    ICONIC_MEDIA_OF_THE_21ST_CENTURY,
    TOP_OSCAR_WINNING_MASTERPIECES,
    TOP_MOST_WATCHED_BLOCKBUSTERS_OF_THE_DECADE,
    TOP_100_SUPERHERO_MEDIA,
    TOP_RATED_IMDB_MEDIA_OF_All_TIME,
    TOP_EMMY_WINNING_SERIES
}
