package org.cyberrealm.tech.muvio.model;

public enum TopLists {
    ICONIC_MOVIES_OF_THE_21ST_CENTURY,
    TOP_OSCAR_WINNING_MASTERPIECES,
    TOP_MOST_WATCHED_BLOCKBUSTERS_OF_THE_DECADE,
    TOP_100_SUPERHERO_MOVIES,
    TOP_RATED_IMDB_MOVIES_OF_All_TIME
}
